# Generated by Django 6.0.5 on 2026-05-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
