# Generated by Django 6.0.5 on 2026-05-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_timesheetentry_end_time_timesheetentry_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='lunch_duration',
            field=models.IntegerField(default=0),
        ),
    ]
