# Generated by Django 6.0.5 on 2026-05-10 04:12

import timesheet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_timesheetentry_lunch_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='id',
            field=models.CharField(default=timesheet.models.generate_short_id, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
