# Generated by Django 6.0.5 on 2026-05-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_alter_timesheetentry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='lunch_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
