"""
Django settings for empyrealtimesheet project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/ dada
"""

from pathlib import Path
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g7aeo&@gif6%s-le#0%lhcw$)b##d8q%1y6wy+rqhd38(styla'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1'
]

AXES_IP_WHITELIST_FIELD = 'HTTP_X_FORWARDED_FOR' # For railway

# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'timesheet',
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'empyrealtimesheet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'empyrealtimesheet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': { 'min_length': 12 } },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator' },
    { 'NAME': 'pwned_passwords_django.validators.PwnedPasswordsValidator' },
    { 'NAME': 'timesheet.validators.ComplexityValidator' },
]

LOGIN_REDIRECT_URL = "home"

LOGOUT_REDIRECT_URL = "login"

# Force all traffic to HTTPS
#SECURE_SSL_REDIRECT = True

# Ensure cookies are only sent over HTTPS
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True

# Prevent browser from "sniffing" content types
#SECURE_CONTENT_TYPE_NOSNIFF = True

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


#CHANGE AT END
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

AUTHENTICATION_BACKENDS = [
    # Axes must be first to intercept the login attempt
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Axes Configuration
AXES_FAILURE_LIMIT = 5            # Number of tries before locking
AXES_COOLOFF_TIME = 1             # How many hours to stay locked out
AXES_RESET_ON_SUCCESS = True      # If they get it right, reset the counter

# Tell Axes to redirect to a specific URL when someone is locked out
AXES_LOCKOUT_TEMPLATE = 'axes/lockout.html'

# Change 'UTC' to your actual timezone, e.g., 'America/New_York' or 'America/Los_Angeles'
TIME_ZONE = 'America/Los_Angeles'

USE_TZ = True

UNFOLD = {
    "SITE_TITLE": "Empyreal Admin",
    "SITE_HEADER": "Empyreal Painting & Construction",
    "SITE_SYMBOL": "speed",  # Pick an icon from Material Symbols
    "COLORS": {
        "primary": {
            "50": "255 247 237",
            "100": "255 237 213",
            "200": "253 186 116",
            "300": "251 146 60",
            "400": "251 146 60",
            "500": "249 115 22",  # This is your #F97316 Vivid Orange
            "600": "234 88 12",
            "700": "194 65 12",
            "800": "154 52 18",
            "900": "124 45 18",
            "950": "67 20 7",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
    },
}